from typing import Protocol

from app.schemas.lead import LeadResponse
from app.schemas.run import AgentRunResponse


class SignalRepository(Protocol):
    async def save_lead(self, lead: LeadResponse) -> None: ...

    async def list_leads(self) -> list[LeadResponse]: ...

    async def get_lead(self, lead_id: str) -> LeadResponse | None: ...

    async def save_agent_run(self, run: AgentRunResponse) -> None: ...

    async def list_agent_runs(self) -> list[AgentRunResponse]: ...

    async def get_agent_run(self, run_id: str) -> AgentRunResponse | None: ...

    async def commit(self) -> None: ...
